language: go

go:
    - 1.x
    - "1.10"
    - "1.11"
    - "1.12"
    - "1.13"
    - "1.14"
    - "1.15"

script:
    - diff -u <(echo -n) <(gofmt -d .)
    - go test -v -race ./...
    - go build ./...
