name: Golang CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    
jobs:
    build-and-test:
        name: Golang CI - test
        runs-on: ubuntu-latest

        strategy:
            matrix:
                go: [1.14.x, 1.15.x]
        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
            - name: Set up Golang
              uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
              with:
                go-version: ${{ matrix.go }}
            - name: Lint
              run: diff -u <(echo -n) <(gofmt -d .)
            - name: Build
              run: go build ./...
            - name: Test
              run: go test -v -race ./...
